CREATE DATABASE Retail_Sales_Dataset;
USE Retail_Sales_Dataset;
CREATE TABLE Orders (
    OrderID VARCHAR(20),
    OrderDate DATE,
    CustomerID VARCHAR(20),
    Product VARCHAR(100),
    Quantity INT,
    UnitPrice DECIMAL(10,2),
    ShippingAddress VARCHAR(255),
    PaymentMethod VARCHAR(50),
    OrderStatus VARCHAR(50),
    TrackingNumber VARCHAR(50),
    ItemsInCart INT,
    CouponCode VARCHAR(50),
    ReferralSource VARCHAR(50),
    TotalPrice DECIMAL(10,2)
);

-- 1.REPLACE NULL VALUES WITH No Coupon TO CouponCode COLUMN
UPDATE orders
SET CouponCode = 'NO COUPON'
WHERE TRIM(CouponCode) = '';

-- 2.VERIFY DATA 
SELECT * FROM orders LIMIT 40;

-- 3.CHECK TOTAL ROWS 
SELECT COUNT(*) FROM orders; 

-- 4.TOTAL NUMBERS OF ORDERS
SELECT COUNT(*) AS Total_Orers 
FROM orders;

-- 5.TOTAL REVENUE GENERATED 
SELECT SUM(TotalPrice) AS Total_Revenue 
FROM orders;

-- 6.AVERAGE ORDER VALUES 
SELECT AVG(TotalPrice) AS Average_Order_Value
FROM orders;

-- 7.DISPLAY DELIVERED ORDERS
SELECT * FROM orders
WHERE OrderStatus = 'Delivered'; 

-- 8.DISPLAY PENDING ORDERS
SELECT * FROM orders
WHERE OrderStatus = 'Pending'; 

-- 9.ORDERS HAVING QUANTITY MORE THAN 3
SELECT * FROM orders
WHERE Quantity > 3;

-- 10.ORDERS PAID THROUGHT A CREDIT CARD 
SELECT * FROM orders 
WHERE PaymentMethod = 'Credit Card';

-- 11.SORT ORDERS BY HIGHEST PRICE 
SELECT * FROM orders 
ORDER BY TotalPrice DESC;

-- 12.SORT ORDERS BY LOWEST  TOTAL PRICE 
SELECT * FROM orders 
ORDER BY TotalPrice ASC; 

-- 13.SORT ORDERS BY DATE
SELECT * 
FROM orders 
ORDER BY OrderDate;

-- 14.NUMBER OF ORDER FOR EACH PRODUCTS
SELECT Product, 
COUNT(*) AS Total_Orders FROM orders 
GROUP BY Product;

-- 15.QUANTITY SOLD BY EACH PRODUCT 
SELECT Product,
SUM(Quantity) AS Quantity_Sold FROM orders
GROUP BY Product
ORDER BY Quantity_Sold DESC;

-- 16.REVENUE GENERATED BY EACH PRODUCT
SELECT Product,
SUM(TotalPrice) AS Revenue FROM orders
GROUP BY Product
ORDER BY Revenue DESC; 

-- 17.AVERAGE QUANTITY PRODUCT 
SELECT Product,
AVG(Quantity) AS Quantity_Product FROM orders 
GROUP BY Product;

-- 18.ORDERS BY PAYMENT METHOD 
SELECT PaymentMethod,
COUNT(*) AS Total_Orders FROM orders
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC;

-- 19.ORDER BY STATUS 
SELECT OrderStatus,
COUNT(*) AS order_status FROM orders 
GROUP BY OrderStatus
ORDER BY order_status DESC;
 
-- MOST USED CouponCode
SELECT CouponCode,
COUNT(*) AS used_CouponCode FROM orders 
GROUP BY CouponCode
ORDER BY used_CouponCode DESC;

-- 20.ORDERS BY DIFFERENT REFERRAL SOURCE   
SELECT ReferralSource,
COUNT(*) AS total_orders FROM orders 
GROUP BY ReferralSource
ORDER BY total_orders DESC;

-- 21.TOP 10 CUSTOMERS BY SPENDING 
SELECT CustomerID,
SUM(TotalPrice) AS total_spend FROM orders 
GROUP BY CustomerID
ORDER BY total_spend DESC
LIMIT 10; 

-- 22.TOP 5 SHIPING LOCAIONS BY ORDERS 
SELECT ShippingAddress,
COUNT(*) AS total_orders FROM Orders
GROUP BY ShippingAddress
ORDER BY total_orders DESC
LIMIT 5;

-- 23.HIGHEST VALUE ORDER 
SELECT * FROM orders
ORDER BY TotalPrice DESC
LIMIT 1;

-- 24.LOWEST VALUE ORDER 
SELECT * FROM orders 
ORDER BY TotalPrice ASC
LIMIT 1;

-- 25.TOTAL QUANTITY SOLD 
SELECT SUM(Quantity) AS Total_Quantity_Sold 
FROM orders;
 
-- 26.AVERAEGE NUMBER OF ITEMS IN CARD 
SELECT AVG(ItemsInCart) AS Average_Items_In_Card
FROM orders;
 
  